### ISSUE TITLE
got some alert when use udp and concurrent>2

### ISSUE THREAD

**Issue by leon2035** [p0pr0ck5/lua-resty-influx#2]
I hvae got some alert where i use ab to benchmark my application,where concurrent >2

2017/02/15 16:08:12 [alert] 14137#0: *121494 send() returned zero (**11: Resource temporarily unavailable**), context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:8071
2017/02/15 15:53:19 [alert] 14137#0: *118585 send() returned zero (115: **Operation now in progress**), context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:8071
2017/02/15 15:41:34 [alert] 14015#0: *114959 send() returned zero (12: **Cannot allocate memory**), context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:8071

**Comment by p0pr0ck5** [comment]
The memory allocation error is odd. Do you see any indication that the host is starved for resources?

It would probably be a good idea to implement a max buffer size to prevent OOM conditions, similar to lua-resty-logger-socket. Patches welcome :)

**Comment by leon2035** [comment]
thanks for you reply,I have implemented a useable version by lua-resty-logger-socket. just pass the msg with line protocol. and work well under high concurrency.

    local influx_data = {
        _measurement = lp.quote_measurement(data.measurement),
        _tag_set = lp.build_tag_set(data.tags),
        _field_set = lp.build_field_set(data.fields),
        _stamp = ngx.now() * 1000
    }

    local msg = lp.build_line_proto_stmt(influx_data)

    logger.log(msg)

**Comment by mudasirmirza** [comment]
Hey guys, can you please provide some sort of working example of pushing metrics in influxDB.

**Comment by p0pr0ck5** [comment]
@mudasirmirza please do not hijack unrelated issues for your own questions. It's very rude and confusing. BTW just have a look at the Readme, there is a usage example for both interfaces. Feel free to open your own issue if you have any questions. Thanks.

**Comment by agentzh** [comment]
@centralman @p0pr0ck5 Sorry for replying to a closed issue. Just for the record, those alerts are completely harmless. I believe ngx_lua module versions no older than 0.8.5 (or OpenResty versions no older than 1.4.1.1) already suppressed those alert level error logs. See also

https://groups.google.com/forum/#!topic/openresty/ndClVSIF9yk

I think @centralman was just using an ancient version of OpenResty or `ngx_lua`. Anyway...

**Comment by p0pr0ck5** [comment]
Thanks for the clarification here @agentzh!
